#!/bin/bash

echo "# note: this file was generated by catreq.sh script.
# please make any new changes in hamr-requirements.txt, and then run the script again.
# any changes to this file will get overwritten when the script is run again." > requirements.txt
cat hamr-requirements.txt apps/*/app/requirements.txt >> requirements.txt
